### ISSUE TITLE
Can you help me

### ISSUE THREAD

**Issue by mkfzdmr** [gmerlino/homebrew-tkgate#1]
checking for strchr... yes
checking for strcspn... yes
checking for strdup... yes
checking for strncasecmp... yes
checking for strrchr... yes
checking for strspn... yes
checking for strstr... yes
checking for strcasestr... yes
checking tcl/tk version... configure: error: could not find tclConfig.sh

how can i fix this?

**Comment by mkfzdmr** [comment]
fixed this problem but i need tkgate last version (2.10b I guess) Can you update your post ?

**Comment by gmerlino** [comment]
Sorry for the late reply, I had an uncommitted fix (since months ago) sitting in my hard disk, just pushed.

This resolved compilation, at least in my setup (macOS Sierra, system Tcl/Tk), but the application segfaults on startup..

I had no time to investigate why.

**Comment by gmerlino** [comment]
I'll close this bug, but feel free to open a new one specific to the issue at hand, i.e., the application crashing
